# -*- coding: utf-8 -*-
"""Model_3_spam_mail_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeczhoCsY4GcDN63UKHpiX-S4jZmgYBO

**Spam Mail Detection**

importing dependencies
"""

import numpy as np
import pandas as pd
import nltk
import nltk.corpus
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

"""Data Collection and Pre-processing"""

raw_main_df = pd.read_csv("/content/drive/MyDrive/DataSets/Data/mail_data.csv")

print(raw_main_df)

raw_main_df.isnull().sum()

#replace the null values with a null string
# raw_main_df = raw_main_df.where((pd.notnull(raw_main_df)),'')
raw_main_df.head()

# checking the number of rows and columns in the dataframe
raw_main_df.shape

"""**Label Encoding**"""

#label encoding, spam - 0 and ham - 1
print(raw_main_df.value_counts('Category'));

label_encoder = LabelEncoder();
labels = label_encoder.fit_transform(raw_main_df.Category)
raw_main_df['Category'] = labels

raw_main_df.value_counts('Category')

"""**One more ways to do level encoding** : 1. mail_data.loc[mail_data['Category']=='spam','Category',]=0;"""

X = raw_main_df['Message']
Y = raw_main_df['Category']

print(X)

print(Y)

"""Spliting the data into training and test dataset"""

x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size=0.2,random_state=3)

print(x_train.shape)

print(x_test.shape)

"""**Features Extraction**"""

#transform the text data to vector that can be used as input to the Logistic Regression
feature_extraction = TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)  #min_df : ignore terms that appear in fewer than min_df documents, stop_words : remove common words like this,is,in,and,etc ,convert the data into lower case
print(feature_extraction)

x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)

# convert Y_train and Y_test values as integers

y_train = y_train.astype('int')
y_test = y_test.astype('int')

print(x_train_features)
print(x_test_features)

"""Training the Model

Logistic Regression Model
"""

model = LogisticRegression()

# training the Logistic Regression model with the training data
model.fit(x_train_features,y_train)

"""Evaluating the training model"""

predicition_on_training_data = model.predict(x_train_features)
accurracy_on_training = accuracy_score(y_train,predicition_on_training_data)

print(accurracy_on_training)

#prediction on the test data
predicition_on_test_data = model.predict(x_test_features)
accuracy_on_test = accuracy_score(y_test,predicition_on_test_data)

print(accuracy_on_test)

"""Builiding a predictive Data"""

input_email = ["As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"]

input_data_features = feature_extraction.transform(input_email)

#making prediction
prediction = model.predict(input_data_features)
if prediction==1:
  print("Spam");
else :
  print("Ham")

